# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Ca3DevOps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deployToProduction:
    runs-on: windows-latest
    needs: DeployToStaging
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Ca3DevOps'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_576B1447F30B4CF6A613484D707D1065 }}
          package: .

  DeployToQA:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'QA'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to QA
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Ca3DevOps'
          slot-name: 'QA'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_QA }}
          package: .

  e2e_tests:
    runs-on: windows-latest
    needs: DeployToQA
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Install Playwright Test dependencies
        run: |
          cd PlaywrightTests
          dotnet add package Microsoft.Playwright.NUnit
          dotnet build
          pwsh bin/Debug/net7.0/playwright.ps1 install

      - name: Run Playwright Tests
        run: dotnet test -- NUnit.NumberOfTestWorkers=5

  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    needs: DeployToQA
  
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: PerformanceTesting/loadTest.js
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

  k6_spike_test:
    name: k6 Spike Test
    runs-on: ubuntu-latest
    needs: DeployToQA
  
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: PerformanceTesting/spikeTest.js
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          
  k6_stress_test:
    name: k6 Stress Test
    runs-on: ubuntu-latest
    needs: DeployToQA
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: PerformanceTesting/stressTest.js
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

  DeployToStaging:
    runs-on: windows-latest
    needs: k6_stress_test
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      - name: Deploy to Staging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Ca3DevOps'
          slot-name: 'Staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGING }}
          package: .

  swap-to-green-slot:
    runs-on: ubuntu-latest
    environment: Production
    needs: deployToProduction
    steps:
        
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
  
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                
      - name: "Swap to green slot"
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az webapp deployment slot swap --slot 'staging' --resource-group ca3 --name Ca3DevOps
      